version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: risqi
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: simpledb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - db_network

volumes:
  postgres_data:

networks:
  db_network:
    driver: bridge
