import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

import SessionWrapper from "@/components/session-provider";
import { cn } from "@/lib/utils";
import "@uploadthing/react/styles.css";
import "./globals.css";
import Appbar from "@/components/appbar";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          fontSans.variable
        )}
      >
        <SessionWrapper>
          <Appbar/>
          {children}</SessionWrapper>
      </body>
    </html>
  );
}
